FUNC LABEL 0
    PRINT VAL 1
    MOV REG 0 VAL 0
    EQU REG 0
    ADD REG 7 REG 0
    CAL VAL 1
    CAL VAL 2
    PRINT REG 0
    RET
FUNC LABEL 1
    PRINT VAL 10
    PRINT VAL 9
    PRINT VAL 8
    PRINT VAL 7
    PRINT VAL 6
    PRINT VAL 5
    PRINT VAL 4
    RET
FUNC LABEL 2
    PRINT VAL 2
    MOV STK A REG 0
    REF STK B STK A
    MOV REG 0 VAL 5
    MOV REG 1 PTR B
    ADD REG 0 REG 1
    ADD REG 7 REG 0
    PRINT VAL 1
    PRINT VAL 2
    PRINT VAL 3
    PRINT VAL 4
    PRINT VAL 5
    PRINT VAL 6
    PRINT VAL 7
    PRINT VAL 8
    PRINT VAL 9
    RET
