FUNC LABEL 0
    MOV STK A VAL 123
    REF STK B STK A
    REF STK C STK B
    REF STK D STK C
    MOV REG 0 STK D
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV STK A REG 0
    MOV STK B PTR A
    MOV STK C PTR B
    MOV STK D PTR C
    PRINT STK D
    RET
