FUNC LABEL 0
    MOV STK A VAL 18
    MOV STK B VAL 42
    REF REG 0 STK A
    CAL VAL 7
    REF REG 0 STK B
    CAL VAL 7
    PRINT STK A
    PRINT STK B
    RET
FUNC LABEL 7
    MOV STK A REG 0
    REF STK B STK A
    MOV REG 0 STK B
    CAL VAL 5
    RET
FUNC LABEL 5
    MOV STK A REG 0
    MOV STK B PTR A
    MOV REG 0 PTR B
    MOV REG 1 VAL 255
    ADD REG 0 REG 1
    MOV PTR B REG 0
    RET
