FUNC LABEL 0
    MOV STK A VAL 1
    MOV STK B VAL 2
    MOV STK C VAL 3
    MOV STK D VAL 4
    MOV STK E VAL 5
    MOV STK F VAL 6
    MOV STK G VAL 7
    MOV STK H VAL 8
    MOV STK I VAL 9
    MOV STK J VAL 10
    MOV STK K VAL 11
    MOV STK L VAL 12
    MOV STK M VAL 13
    MOV STK N VAL 14
    MOV STK O VAL 15
    MOV STK P VAL 16
    MOV STK Q VAL 17
    MOV STK R VAL 18
    MOV STK S VAL 19
    MOV STK T VAL 20
    MOV STK U VAL 21
    MOV STK V VAL 22
    MOV STK W VAL 23
    MOV STK X VAL 24
    MOV STK Y VAL 25
    MOV STK Z VAL 26
    MOV STK a VAL 27
    MOV STK b VAL 28
    MOV STK c VAL 29
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV STK A VAL 1
    MOV STK B VAL 2
    MOV STK C VAL 3
    MOV STK D VAL 4
    MOV STK E VAL 5
    MOV STK F VAL 6
    MOV STK G VAL 7
    MOV STK H VAL 8
    MOV STK I VAL 9
    MOV STK J VAL 10
    MOV STK K VAL 11
    MOV STK L VAL 12
    MOV STK M VAL 13
    MOV STK N VAL 14
    MOV STK O VAL 15
    MOV STK P VAL 16
    MOV STK Q VAL 17
    MOV STK R VAL 18
    MOV STK S VAL 19
    MOV STK T VAL 20
    MOV STK U VAL 21
    MOV STK V VAL 22
    MOV STK W VAL 23
    MOV STK X VAL 24
    MOV STK Y VAL 25
    MOV STK Z VAL 26
    MOV STK a VAL 3
    MOV STK b VAL 28
    MOV STK c VAL 29
    PRINT STK a
    RET
